language: node_js

os:
  - linux
  - osx
  - windows

node_js:
  - 12 # current
  - 10 # lts
  - 8

# Travis uses yarn@1.15.2 on linux, and yarn@latest on other platforms.
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH
